platform :ios, '9.0'
use_frameworks!

target 'ITMVVMDemo' do
    #pod 'AFNetworking'
    pod 'Masonry'
    pod 'GCJSONKit'
    pod 'SDWebImage'
    pod 'SDAutoLayout'
    pod 'ASIHTTPRequest', '~> 1.8.2'
    pod 'MJRefresh'
    pod 'YTKNetwork'
    pod 'JSONModel'
    pod 'CocoaLumberjack'
end